server:
  port: 8010
spring:
  application:
    name: user-proxy
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: userdomain
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: "${spring.application.name}:${random.value}"
user-proxy:
  ribbon:
    ServerListRefreshInterval: 2000